//
//  SettingsView.swift
//  WalkWorthy
//
//  Settings and account management.
//

import SwiftUI

struct SettingsView: View {
    @EnvironmentObject private var appState: AppState
    private let config = Config.shared

    // MARK: - Account deletion state
    // Account deletion is required for App Store Guideline 5.1.1(v).
    @State private var showDeleteConfirmation = false
    @State private var showReauthSheet = false
    @State private var isDeletingAccount = false
    @State private var deleteAccountError: String?

    var body: some View {
        NavigationStack {
            ZStack {
                TimeOfDayTheme.current.backdrop
                    .ignoresSafeArea()

                Form {
                    Section("Personalization") {
                        NavigationLink {
                            OnboardingForm()
                        } label: {
                            Label("Edit personal details", systemImage: "person.crop.circle")
                        }
                        .listRowBackground(Color.wwCardBackground)

                        // Bible translation picker removed until multi-translation
                        // content is actually shipped. Today the app uses ESV
                        // everywhere (Verse of the Day, AI encouragements), so a
                        // 7-option picker would be misleading. AppState still tracks
                        // selectedTranslation (default ESV) and the backend schema
                        // accepts all 7 values, so re-adding the picker is a small
                        // diff — restore this Picker, setTranslation, and
                        // syncStoredProfile when real translation content lands.
                    }

                    // In-app AI disclosure required by App Review Guideline
                    // 5.1.2(i) — mirrors the one-time AIConsentView shown
                    // before the first check-in.
                    Section {
                        Toggle(isOn: Binding(
                            get: { appState.useProfilePersonalization },
                            set: { appState.setUseProfilePersonalization($0) }
                        )) {
                            Text("Use profile for encouragements")
                        }
                        .listRowBackground(Color.wwCardBackground)

                        Toggle(isOn: Binding(
                            get: { appState.analyticsEnabled },
                            set: { appState.setAnalyticsEnabled($0) }
                        )) {
                            Text("Share anonymous usage analytics")
                        }
                        .listRowBackground(Color.wwCardBackground)
                    } header: {
                        Text("AI & Your Data")
                    } footer: {
                        Text("Encouragements and reflections are generated by OpenAI, configured for zero data retention. Check-ins send your mood, tags, and optional note; with the profile toggle on, your age range, occupation or major, and hobbies are included — never your name. Analytics (Firebase) counts feature usage and never includes your check-ins or notes.\n\nWalkWorthy offers Scripture-based encouragement, not medical or mental-health care. If you're struggling, call or text 988.")
                    }

                    Section("Notifications") {
                        NavigationLink {
                            NotificationSettingsView()
                        } label: {
                            Label("Check-in reminders", systemImage: "bell.badge")
                        }
                        .listRowBackground(Color.wwCardBackground)
                    }

                    Section("Data") {
                        NavigationLink {
                            MoodLogView()
                        } label: {
                            Label("Check-in log", systemImage: "list.bullet.rectangle")
                        }
                        .listRowBackground(Color.wwCardBackground)
                    }

                    Section("Account") {
                        Button(role: .destructive) {
                            appState.signOut()
                        } label: {
                            Label("Sign out", systemImage: "rectangle.portrait.and.arrow.right")
                        }
                        .disabled(!appState.isAuthenticated || isDeletingAccount)
                        .listRowBackground(Color.wwCardBackground)

                        Button(role: .destructive) {
                            showDeleteConfirmation = true
                        } label: {
                            HStack {
                                Label("Delete account", systemImage: "trash")
                                if isDeletingAccount {
                                    Spacer()
                                    ProgressView()
                                        .controlSize(.small)
                                }
                            }
                        }
                        .disabled(!appState.isAuthenticated || isDeletingAccount)
                        .listRowBackground(Color.wwCardBackground)
                    }

                    Section("About") {
                        LabeledContent("Build", value: Bundle.main.versionString)
                            .listRowBackground(Color.wwCardBackground)
                        Link(destination: URL(string: "https://walkworthy-app.web.app/privacy")!) {
                            HStack {
                                Text("Privacy Policy")
                                Spacer()
                                Image(systemName: "arrow.up.right.square")
                                    .foregroundStyle(.secondary)
                            }
                        }
                        .listRowBackground(Color.wwCardBackground)
                        Link(destination: URL(string: "https://walkworthy-app.web.app/terms")!) {
                            HStack {
                                Text("Terms of Use")
                                Spacer()
                                Image(systemName: "arrow.up.right.square")
                                    .foregroundStyle(.secondary)
                            }
                        }
                        .listRowBackground(Color.wwCardBackground)
                        Link(destination: URL(string: "mailto:walkworthyofficial@gmail.com")!) {
                            HStack {
                                Text("Contact Support")
                                Spacer()
                                Image(systemName: "envelope")
                                    .foregroundStyle(.secondary)
                            }
                        }
                        .listRowBackground(Color.wwCardBackground)
                    }
                }
                .scrollContentBackground(.hidden)
                .navigationTitle("Settings")
                .confirmationDialog(
                    "Delete Account?",
                    isPresented: $showDeleteConfirmation,
                    titleVisibility: .visible
                ) {
                    Button("Delete Account", role: .destructive) {
                        Task { await startAccountDeletion() }
                    }
                    Button("Cancel", role: .cancel) {}
                } message: {
                    Text("This permanently removes your profile, mood history, journal entries, daily reflections, and encouragements. This cannot be undone.")
                }
                .sheet(isPresented: $showReauthSheet) {
                    ReauthenticationSheet(
                        onAuthenticated: {
                            // Sheet dismisses itself before calling us; continue
                            // straight to the backend delete.
                            Task { await performBackendDeletion() }
                        }
                    )
                }
                .alert(
                    "Couldn't delete account",
                    isPresented: Binding(
                        get: { deleteAccountError != nil },
                        set: { if !$0 { deleteAccountError = nil } }
                    ),
                    presenting: deleteAccountError
                ) { _ in
                    Button("OK", role: .cancel) { deleteAccountError = nil }
                } message: { message in
                    Text(message)
                }
            }
        }
    }

    // MARK: - Account deletion flow
    //
    // Two-step: (1) if the session is stale, prompt for password re-auth via
    // ReauthenticationSheet — on success it calls `performBackendDeletion()`.
    // (2) otherwise skip straight to the backend call. Local cleanup only runs
    // after the backend confirms success so a network failure never strands the
    // user's on-device data in a half-deleted state.

    private func startAccountDeletion() async {
        guard appState.isAuthenticated, !isDeletingAccount else { return }
        isDeletingAccount = true

        let needsReauth = await appState.accountDeletionRequiresReauth()
        if needsReauth {
            // Hand off to the re-auth sheet. It clears isDeletingAccount on
            // cancel; on success it calls performBackendDeletion() which
            // handles the spinner + error alerts.
            isDeletingAccount = false
            showReauthSheet = true
        } else {
            await performBackendDeletion()
        }
    }

    private func performBackendDeletion() async {
        isDeletingAccount = true
        defer { isDeletingAccount = false }

        do {
            try await appState.deleteAccount()
            // Success: the Firebase auth state listener will flip
            // isAuthenticated to false, which drives the RootView back to
            // TitleScreenView. Belt-and-suspenders signOut() in case the
            // listener is slow on a flaky network.
            appState.signOut()
        } catch APIError.unauthorized, APIError.notAuthenticated {
            deleteAccountError = "Please sign in again, then try deleting your account."
            // Force a sign-out so the user returns to TitleScreenView. The
            // alert above also surfaces the reason.
            appState.signOut()
        } catch let error as APIError {
            deleteAccountError = error.errorDescription ?? "Couldn't delete account — please try again."
        } catch {
            deleteAccountError = "Couldn't delete account — please try again."
            #if DEBUG
            print("[SettingsView] deleteAccount failed: \(error)")
            #endif
        }
    }
}

// MARK: - Re-auth sheet

/// Password-only re-authentication sheet shown before account deletion when
/// the Firebase session is older than the sensitive-operation window.
/// Firebase requires `user.reauthenticate(with:)` for destructive actions;
/// the backend also enforces a token-freshness check on `/deleteAccount`.
/// Internal (not private) so EmailVerificationView can reuse it for the
/// pre-verification delete-account path.
struct ReauthenticationSheet: View {
    /// Called once re-authentication succeeds. The sheet dismisses itself
    /// before invoking this closure so the caller can immediately present
    /// the next UI step (a progress indicator on the destructive action).
    let onAuthenticated: () -> Void

    @EnvironmentObject private var appState: AppState
    @Environment(\.dismiss) private var dismiss

    @State private var password: String = ""
    @State private var isSubmitting: Bool = false
    @State private var errorMessage: String?
    @FocusState private var passwordFocused: Bool

    var body: some View {
        NavigationStack {
            ZStack {
                TimeOfDayTheme.current.backdrop
                    .ignoresSafeArea()

                Form {
                    Section {
                        Text("For your security, please re-enter your password to confirm account deletion.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .listRowBackground(Color.wwCardBackground)
                    }

                    Section("Password") {
                        SecureField("Password", text: $password)
                            .textContentType(.password)
                            .submitLabel(.continue)
                            .focused($passwordFocused)
                            .onSubmit { submit() }
                            .listRowBackground(Color.wwCardBackground)
                    }

                    if let errorMessage {
                        Section {
                            Text(errorMessage)
                                .font(.subheadline)
                                .foregroundStyle(.red)
                                .listRowBackground(Color.wwCardBackground)
                        }
                    }
                }
                .scrollContentBackground(.hidden)
                .disabled(isSubmitting)
            }
            .navigationTitle("Confirm Password")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                    .disabled(isSubmitting)
                }
                ToolbarItem(placement: .confirmationAction) {
                    if isSubmitting {
                        ProgressView()
                    } else {
                        Button("Continue") { submit() }
                            .disabled(password.isEmpty)
                    }
                }
            }
            .task {
                // Slight delay so the sheet's entrance animation doesn't race
                // the keyboard — matches the pattern in SignInFormView.
                try? await Task.sleep(for: .milliseconds(300))
                passwordFocused = true
            }
        }
    }

    private func submit() {
        guard !isSubmitting, !password.isEmpty else { return }
        isSubmitting = true
        errorMessage = nil

        Task {
            do {
                try await appState.reauthenticate(password: password)
                // Dismiss first so the parent can immediately present its
                // progress indicator on the Settings screen without the sheet
                // flashing over it.
                dismiss()
                onAuthenticated()
            } catch {
                let details = FirebaseAuthErrorMapper.mapError(error)
                errorMessage = details.displayText
                isSubmitting = false
            }
        }
    }
}

enum ReminderType {
    case morning
    case midday
    case evening
}

struct NotificationSettingsView: View {
    @EnvironmentObject private var appState: AppState
    @State private var morningTime = defaultTime(hour: 7, minute: 0)
    @State private var middayTime = defaultTime(hour: 12, minute: 0)
    @State private var eveningTime = defaultTime(hour: 19, minute: 0)
    @State private var morningEnabled = true
    @State private var middayEnabled = true
    @State private var eveningEnabled = true
    @State private var showNotificationDeniedAlert = false
    @State private var pendingAuthorizationFor: ReminderType?

    private let defaults = UserDefaults.standard

    /// Scopes reminder preference keys to the signed-in user so shared
    /// devices don't leak one account's notification schedule to another.
    /// Falls back to the bare key only for pre-auth reads — those should
    /// never occur in practice because this view requires authentication.
    private func scopedKey(_ baseKey: String) -> String {
        guard let userSub = appState.authenticatedUserSub else { return baseKey }
        return "\(baseKey)::\(userSub)"
    }

    var body: some View {
        ZStack {
            TimeOfDayTheme.current.backdrop
                .ignoresSafeArea()

            Form {
                Section {
                    Text("Choose when you'd like to receive check-in reminders. We'll send a gentle nudge at each time you enable.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .listRowBackground(Color.wwCardBackground)
                }

                Section("Morning") {
                    Toggle("Enable morning reminder", isOn: Binding(
                        get: { morningEnabled },
                        set: { handleMorningToggle(newValue: $0) }
                    ))
                    .listRowBackground(Color.wwCardBackground)
                    if morningEnabled {
                        DatePicker("Time", selection: $morningTime, displayedComponents: .hourAndMinute)
                            .listRowBackground(Color.wwCardBackground)
                    }
                }

                Section("Midday") {
                    Toggle("Enable midday reminder", isOn: Binding(
                        get: { middayEnabled },
                        set: { handleMiddayToggle(newValue: $0) }
                    ))
                    .listRowBackground(Color.wwCardBackground)
                    if middayEnabled {
                        DatePicker("Time", selection: $middayTime, displayedComponents: .hourAndMinute)
                            .listRowBackground(Color.wwCardBackground)
                    }
                }

                Section("Evening") {
                    Toggle("Enable evening reminder", isOn: Binding(
                        get: { eveningEnabled },
                        set: { handleEveningToggle(newValue: $0) }
                    ))
                    .listRowBackground(Color.wwCardBackground)
                    if eveningEnabled {
                        DatePicker("Time", selection: $eveningTime, displayedComponents: .hourAndMinute)
                            .listRowBackground(Color.wwCardBackground)
                    }
                }

                Section {
                    Text("Notification times are stored on your device. Actual reminder delivery depends on your notification permissions.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .listRowBackground(Color.wwCardBackground)
                }
            }
            .scrollContentBackground(.hidden)
            .navigationTitle("Check-in Reminders")
            .navigationBarTitleDisplayMode(.inline)
        .onAppear {
            loadSavedSettings()
        }
        .onChange(of: morningTime) { _, _ in
            saveAndSchedule()
        }
        .onChange(of: middayTime) { _, _ in
            saveAndSchedule()
        }
        .onChange(of: eveningTime) { _, _ in
            saveAndSchedule()
        }
        .alert("Notifications Disabled", isPresented: $showNotificationDeniedAlert) {
            Button("Open Settings") {
                openAppSettings()
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("Check-in reminders require notification permissions. Please enable notifications in Settings to receive reminders.")
        }
        }
    }

    private func handleMorningToggle(newValue: Bool) {
        if !newValue {
            morningEnabled = false
            saveAndSchedule()
            return
        }
        morningEnabled = true
        pendingAuthorizationFor = .morning
        checkAuthorizationAndSchedule()
    }

    private func handleMiddayToggle(newValue: Bool) {
        if !newValue {
            middayEnabled = false
            saveAndSchedule()
            return
        }
        middayEnabled = true
        pendingAuthorizationFor = .midday
        checkAuthorizationAndSchedule()
    }

    private func handleEveningToggle(newValue: Bool) {
        if !newValue {
            eveningEnabled = false
            saveAndSchedule()
            return
        }
        eveningEnabled = true
        pendingAuthorizationFor = .evening
        checkAuthorizationAndSchedule()
    }

    private func checkAuthorizationAndSchedule() {
        Task {
            // Resolves the current permission state, prompting the user if it
            // hasn't been determined yet.
            let outcome = await NotificationScheduler.shared.resolveAuthorization()
            await MainActor.run {
                switch outcome {
                case .authorized:
                    self.saveAndSchedule()
                case .denied:
                    if let reminderType = self.pendingAuthorizationFor {
                        self.disableToggle(for: reminderType)
                    }
                    self.showNotificationDeniedAlert = true
                }
            }
        }
    }

    private func disableToggle(for reminderType: ReminderType) {
        // Disable the specific toggle that triggered authorization
        switch reminderType {
        case .morning:
            morningEnabled = false
        case .midday:
            middayEnabled = false
        case .evening:
            eveningEnabled = false
        }
        // Clear the pending authorization tracker
        pendingAuthorizationFor = nil
    }

    private func openAppSettings() {
        guard let settingsUrl = URL(string: UIApplication.openSettingsURLString) else {
            return
        }
        UIApplication.shared.open(settingsUrl)
    }

    /// One-shot migration: older TestFlight builds wrote reminder preferences
    /// under the bare (unscoped) key. When we introduced per-user scoping, any
    /// existing value stopped being read — which looked like "reminders silently
    /// reset" to those users. This copies the bare value to the scoped slot on
    /// first read and removes the bare key so we don't migrate twice.
    /// Idempotent: once the scoped slot exists the helper is a no-op.
    private func migrateReminderKeyIfNeeded(bare: String) {
        guard let userSub = appState.authenticatedUserSub else { return }
        let scoped = "\(bare)::\(userSub)"
        if defaults.object(forKey: scoped) == nil,
           let value = defaults.object(forKey: bare) {
            defaults.set(value, forKey: scoped)
            defaults.removeObject(forKey: bare)
        }
    }

    private func loadSavedSettings() {
        // Migrate any legacy unscoped reminder keys into the per-user scope so
        // existing TestFlight users retain their reminder times and toggles.
        let legacyKeys = [
            StorageKeys.morningEnabled,
            StorageKeys.middayEnabled,
            StorageKeys.eveningEnabled,
            StorageKeys.morningHour,
            StorageKeys.morningMinute,
            StorageKeys.middayHour,
            StorageKeys.middayMinute,
            StorageKeys.eveningHour,
            StorageKeys.eveningMinute,
        ]
        for key in legacyKeys {
            migrateReminderKeyIfNeeded(bare: key)
        }

        let morningEnabledKey = scopedKey(StorageKeys.morningEnabled)
        let middayEnabledKey = scopedKey(StorageKeys.middayEnabled)
        let eveningEnabledKey = scopedKey(StorageKeys.eveningEnabled)
        let morningHourKey = scopedKey(StorageKeys.morningHour)
        let morningMinuteKey = scopedKey(StorageKeys.morningMinute)
        let middayHourKey = scopedKey(StorageKeys.middayHour)
        let middayMinuteKey = scopedKey(StorageKeys.middayMinute)
        let eveningHourKey = scopedKey(StorageKeys.eveningHour)
        let eveningMinuteKey = scopedKey(StorageKeys.eveningMinute)

        // Load enabled states
        if defaults.object(forKey: morningEnabledKey) != nil {
            morningEnabled = defaults.bool(forKey: morningEnabledKey)
        }
        if defaults.object(forKey: middayEnabledKey) != nil {
            middayEnabled = defaults.bool(forKey: middayEnabledKey)
        }
        if defaults.object(forKey: eveningEnabledKey) != nil {
            eveningEnabled = defaults.bool(forKey: eveningEnabledKey)
        }

        // Load times
        if let morningHour = defaults.object(forKey: morningHourKey) as? Int,
           let morningMinute = defaults.object(forKey: morningMinuteKey) as? Int {
            morningTime = Self.defaultTime(hour: morningHour, minute: morningMinute)
        }
        if let middayHour = defaults.object(forKey: middayHourKey) as? Int,
           let middayMinute = defaults.object(forKey: middayMinuteKey) as? Int {
            middayTime = Self.defaultTime(hour: middayHour, minute: middayMinute)
        }
        if let eveningHour = defaults.object(forKey: eveningHourKey) as? Int,
           let eveningMinute = defaults.object(forKey: eveningMinuteKey) as? Int {
            eveningTime = Self.defaultTime(hour: eveningHour, minute: eveningMinute)
        }
    }

    private func saveAndSchedule() {
        // Save enabled states
        defaults.set(morningEnabled, forKey: scopedKey(StorageKeys.morningEnabled))
        defaults.set(middayEnabled, forKey: scopedKey(StorageKeys.middayEnabled))
        defaults.set(eveningEnabled, forKey: scopedKey(StorageKeys.eveningEnabled))

        // Save times
        let calendar = Calendar.current
        let morningComponents = calendar.dateComponents([.hour, .minute], from: morningTime)
        let middayComponents = calendar.dateComponents([.hour, .minute], from: middayTime)
        let eveningComponents = calendar.dateComponents([.hour, .minute], from: eveningTime)

        defaults.set(morningComponents.hour, forKey: scopedKey(StorageKeys.morningHour))
        defaults.set(morningComponents.minute, forKey: scopedKey(StorageKeys.morningMinute))
        defaults.set(middayComponents.hour, forKey: scopedKey(StorageKeys.middayHour))
        defaults.set(middayComponents.minute, forKey: scopedKey(StorageKeys.middayMinute))
        defaults.set(eveningComponents.hour, forKey: scopedKey(StorageKeys.eveningHour))
        defaults.set(eveningComponents.minute, forKey: scopedKey(StorageKeys.eveningMinute))

        // Schedule notifications
        Task {
            await scheduleReminders()
        }
    }

    private func scheduleReminders() async {
        let calendar = Calendar.current
        var reminders: [NotificationScheduler.DailyReminder] = []

        if morningEnabled {
            let components = calendar.dateComponents([.hour, .minute], from: morningTime)
            reminders.append(NotificationScheduler.DailyReminder(
                id: StorageKeys.morningNotificationId,
                title: "Morning Check-in",
                body: "How are you feeling about today?",
                hour: components.hour ?? 7,
                minute: components.minute ?? 0
            ))
        }

        if middayEnabled {
            let components = calendar.dateComponents([.hour, .minute], from: middayTime)
            reminders.append(NotificationScheduler.DailyReminder(
                id: StorageKeys.middayNotificationId,
                title: "Midday Check-in",
                body: "How is your day going so far?",
                hour: components.hour ?? 12,
                minute: components.minute ?? 0
            ))
        }

        if eveningEnabled {
            let components = calendar.dateComponents([.hour, .minute], from: eveningTime)
            reminders.append(NotificationScheduler.DailyReminder(
                id: StorageKeys.eveningNotificationId,
                title: "Evening Check-in",
                body: "How was your day?",
                hour: components.hour ?? 19,
                minute: components.minute ?? 0
            ))
        }

        // The scheduler always clears the old requests first so disabled
        // reminders are removed even when nothing new is scheduled.
        await NotificationScheduler.shared.replaceDailyReminders(reminders, clearing: [
            StorageKeys.morningNotificationId,
            StorageKeys.middayNotificationId,
            StorageKeys.eveningNotificationId
        ])
    }

    private static func defaultTime(hour: Int, minute: Int) -> Date {
        var components = DateComponents()
        components.hour = hour
        components.minute = minute
        return Calendar.current.date(from: components) ?? Date()
    }

    private enum StorageKeys {
        static let morningEnabled = "walkworthy.reminders.morningEnabled"
        static let middayEnabled = "walkworthy.reminders.middayEnabled"
        static let eveningEnabled = "walkworthy.reminders.eveningEnabled"
        static let morningHour = "walkworthy.reminders.morningHour"
        static let morningMinute = "walkworthy.reminders.morningMinute"
        static let middayHour = "walkworthy.reminders.middayHour"
        static let middayMinute = "walkworthy.reminders.middayMinute"
        static let eveningHour = "walkworthy.reminders.eveningHour"
        static let eveningMinute = "walkworthy.reminders.eveningMinute"
        static let morningNotificationId = "walkworthy.reminder.morning"
        static let middayNotificationId = "walkworthy.reminder.midday"
        static let eveningNotificationId = "walkworthy.reminder.evening"
    }
}

private extension Bundle {
    var versionString: String {
        let version = object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "1.0"
        let build = object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "1"
        return "v\(version) (\(build))"
    }
}
